[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui : UI autotests
    regression : For regress TCs
    smoke : Smoke TCs
    registration : TCs for registration
    dashboard : For critical TCS with dashboard
    slow : Slow speed TCs
    critical : For critical TCs
    authorization : TCs for authorization scope
    courses : TCs for courses tab
    flaky : For not stable tests